import Head from 'next/head';
import Navigationbar from './components/navigationbar';
import Welcomebanner from './components/welcomebanner';
import Cards from './components/cards';

export default function Home({ data }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Navigationbar/>
     <Welcomebanner/>
     <div 
      style={{display:'flex', justifyContent: 'center'}}
    >
      {data.map((item, i) => (
        <Cards
          key={i}
          name={item.name}
          age={item.age}
          isMale={item.isMale}
          breed={item.breed}
        />
      ))}
     </div>
    </>
  )
}

export async function getStaticProps() {

  const res = await fetch('http://localhost:3000/api/dogs')
  const data = await res.json()

  return {
    props: {
      data
    },
  }
}